import { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';

const LanguageContext = createContext(null);

const SUPPORTED = ['fr', 'en'];
const DEFAULT_LANGUAGE = 'en';

const TRANSLATIONS = {
    fr: {
        // Mobile tabs
        tab_home: 'Accueil',
        tab_search: 'Rechercher',
        tab_feed: 'Actualités',
        tab_library: 'Bibliothèque',
        tab_profile: 'Profil',

        // Profile settings
        settings_title: 'Paramètres du profil',
        settings_edit_profile: 'Modifier le profil',
        settings_profile_picture: 'Photo de profil',
        settings_image_hint: 'JPEG, PNG, WebP ou GIF. Max 5 Mo.',
        settings_info: 'Informations',
        settings_username: 'Nom d\'utilisateur',
        settings_username_placeholder: 'Votre pseudo',
        settings_bio: 'Bio',
        settings_bio_placeholder: 'Parlez-nous un peu de vous...',
        settings_website: 'Site web',
        settings_website_placeholder: 'https://votresite.com',
        settings_save: 'Enregistrer les modifications',
        settings_saving: 'Enregistrement...',
        settings_saved: 'Profil enregistré.',
        settings_avatar_updated: 'Photo de profil mise à jour.',
        settings_preferences: 'Préférences',
        settings_theme: 'Thème',
        settings_language: 'Langue',
        settings_language_saving: 'Sauvegarde...',
        settings_choose: 'Choisir',
        settings_upload: 'Envoyer',
        settings_loading_profile: 'Chargement du profil...',
        settings_login_required: 'Connexion requise',
        settings_login_to_edit: 'Connectez-vous pour modifier votre profil.',
        settings_log_in: 'Se connecter',
        settings_unsupported_format: 'Format non supporté. Utilisez JPEG, PNG, WebP ou GIF.',
        settings_too_large: 'L\'image ne doit pas dépasser 5 Mo.',
        settings_upload_failed: 'Échec de l\'upload. Réessayez.',
        settings_failed_save: 'Impossible d\'enregistrer le profil.',
        settings_username_min: 'Le nom d\'utilisateur doit contenir entre 3 et 50 caractères.',
        settings_bio_max: 'La bio ne peut pas dépasser',
        settings_bio_max_chars: 'caractères.',
        settings_website_invalid: 'Le site web doit commencer par http:// ou https://.',

        // Stats
        stats_title: 'Statistiques',
        stats_total: 'Total',
        stats_done: 'Terminés',
        stats_reviews: 'Critiques',
        stats_lists: 'Listes',
        stats_content_type: 'TYPE DE CONTENU',
        stats_movies: 'Films',
        stats_series: 'Séries',
        stats_watch_time: 'TEMPS DE VISIONNAGE',
        stats_watch_time_sub: 'films terminés',
        stats_avg_rating: 'NOTE MOYENNE',
        stats_no_ratings: 'Pas encore noté',
        stats_to_watch: 'À voir',
        stats_watching: 'En cours',
        stats_completed: 'Terminés',
        stats_dropped: 'Abandonnés',

        // Login
        login_welcome_back: 'Bienvenue',
        login_subtitle: 'Connectez-vous à votre compte',
        login_email: 'Email',
        login_password: 'Mot de passe',
        login_signing_in: 'Connexion...',
        login_submit: 'Se connecter',
        login_or: 'ou',
        login_google: 'Continuer avec Google',
        login_no_account: 'Pas de compte ?',
        login_sign_up: "S'inscrire",

        // Register
        register_title: 'Créer un compte',
        register_subtitle: 'Rejoignez moviemovie',
        register_username: "Nom d'utilisateur",
        register_creating: 'Création en cours...',
        register_submit: "S'inscrire",
        register_already: 'Déjà un compte ?',
        register_sign_in: 'Se connecter',
        register_pw_min: 'Au moins 8 caractères',
        register_pw_upper: 'Une lettre majuscule',
        register_pw_lower: 'Une lettre minuscule',
        register_pw_number: 'Un chiffre',

        // Profile
        profile_loading: 'Chargement...',
        profile_member_since: 'Membre depuis',
        profile_no_bio: 'Pas encore de bio.',
        profile_followers: 'abonnés',
        profile_following: 'abonnements',
        profile_edit: 'Modifier le profil',
        profile_follow: 'Suivre',
        profile_following_btn: 'Abonné(e)',
        profile_unfollow: 'Se désabonner',
        profile_saving: 'Sauvegarde...',
        profile_my_collection: 'Ma collection',
        profile_see_all: 'Voir tout',
        profile_no_media: 'Aucun média pour l\'instant.',
        profile_my_lists: 'Mes listes',
        profile_public_lists: 'listes publiques',
        profile_no_lists: 'Aucune liste pour l\'instant.',
        profile_no_public_lists: 'Aucune liste publique.',
        profile_items: 'éléments',
        profile_lists: 'listes',
        profile_sign_out: 'Déconnexion',
        profile_followers_title: 'Abonnés',
        profile_following_title: 'Abonnements',
        profile_no_users: 'Aucun utilisateur.',
        profile_go_back: 'Retour',
        profile_unable_load: 'Impossible de charger ce profil.',
        profile_message: 'Message',
        profile_guest: 'Invité',
        profile_guest_browse: 'Parcourez le contenu public sans compte.',
        profile_guest_login_desc: 'Connectez-vous pour gérer votre bibliothèque, critiques, fil d\'actualité et messages.',
        profile_login: 'Se connecter',
        profile_create_account: 'Créer un compte',

        // Library
        lib_my_collection: 'Ma collection',
        lib_my_lists: 'Mes listes',
        lib_loading: 'Chargement...',
        lib_guest_title: 'Bibliothèque',
        lib_guest_body: 'Connectez-vous pour gérer votre collection et vos listes.',
        lib_all: 'Tout',
        lib_no_items: 'Aucun média dans cette collection.',
        lib_new_list_placeholder: 'Nom de la nouvelle liste...',
        lib_public: 'Publique',
        lib_creating: 'Création...',
        lib_create: '+ Créer',
        lib_no_lists: 'Aucune liste. Créez-en une ci-dessus !',
        lib_delete_title: 'Supprimer cette liste ?',
        lib_delete_msg: 'Cette action est irréversible.',
        lib_cancel: 'Annuler',
        lib_delete: 'Supprimer',
        lib_items: 'éléments',
        lib_lists: 'listes',

        // Home
        home_title: 'Découvrez des milliers de films et séries.',
        home_subtitle: 'Recherchez, découvrez et suivez votre contenu préféré.',
        home_search_placeholder: 'Rechercher un film ou une série...',
        home_search_btn: 'Rechercher',
        home_trending: 'Tendances du moment',
        home_all: 'Tout',
        home_movies: 'Films',
        home_series: 'Séries',
        home_loading: 'Chargement des tendances...',
        home_error: 'Impossible de charger les tendances.',
        home_retry: 'Réessayer',
        home_movie_label: 'Film',
        home_series_label: 'Série',

        // Mobile login
        mob_login_title: 'Connexion',
        mob_login_subtitle: 'Accédez à votre bibliothèque, critiques, fil et messages.',
        mob_login_required: 'Email et mot de passe requis.',
        mob_login_error: 'Impossible de se connecter.',
        mob_login_new: 'Nouveau sur moviemovie ?',
        mob_login_create: 'Créer un compte',

        // Mobile register
        mob_register_title: 'Créer un compte',
        mob_register_subtitle: 'Rejoignez la communauté et commencez à construire votre bibliothèque.',
        mob_register_required: 'Nom d\'utilisateur, email et mot de passe requis.',
        mob_register_error: 'Impossible de créer votre compte.',
        mob_register_already: 'Déjà un compte ?',
        mob_register_sign_in: 'Se connecter',

        // Mobile search
        mob_search_placeholder: 'Rechercher films, séries, utilisateurs, listes...',
        mob_search_movies: 'Films',
        mob_search_series: 'Séries',
        mob_search_users: 'Utilisateurs',
        mob_search_lists: 'Listes',
        mob_search_sort_popular: 'Populaire',
        mob_search_sort_top: 'Mieux notés',
        mob_search_sort_newest: 'Récent',
        mob_search_sort_oldest: 'Ancien',
        mob_search_rating_any: 'Toute note',
        mob_search_filters: 'Filtres',
        mob_search_year: 'Année',
        mob_search_clear: 'Effacer',
        mob_search_all_genres: 'Tous genres',
        mob_search_discover: 'Recherche ou découverte par filtres',
        mob_search_searching: 'Recherche en cours...',
        mob_search_min_chars: 'Saisissez au moins 2 caractères',
        mob_search_error: 'Une erreur est survenue',
        mob_search_no_results: 'Aucun résultat',
        mob_search_prev: 'Précédent',
        mob_search_next: 'Suivant',
        mob_search_by: 'par',
        mob_search_member: 'Membre moviemovie',
        mob_search_year_hint: 'Saisissez une année à 4 chiffres.',
        mob_search_chars_hint: 'Saisissez au moins 2 caractères.',
        mob_search_failed: 'Recherche échouée.',
        mob_search_page_error: 'Entrez une page entre 1 et',
        mob_search_title: 'Rechercher',

        // Feed
        feed_title: 'Fil d\'actualité',
        feed_loading: 'Chargement du fil...',
        feed_error: 'Impossible de charger votre fil.',
        feed_empty_title: 'Rien pour l\'instant',
        feed_empty_body: 'Suivez des utilisateurs pour voir leur activité ici.',
        feed_login_prompt: 'Connectez-vous pour voir l\'activité des personnes que vous suivez.',
        feed_login: 'Se connecter',
        feed_added_to: 'a ajouté dans',
        feed_updated: 'a mis à jour sa collection',
        feed_reviewed: 'a écrit une critique',
        feed_unknown_title: 'Titre inconnu',

        // Notifications
        notif_title: 'Notifications',
        notif_loading: 'Chargement des notifications...',
        notif_error: 'Impossible de charger les notifications.',
        notif_empty_title: 'Aucune notification',
        notif_empty_body: 'Vous verrez ici les likes, commentaires et nouveaux abonnés.',
        notif_read_all: 'Tout lire',
        notif_liked: 'a aimé votre critique',
        notif_commented: 'a commenté votre critique',
        notif_following: 'a commencé à vous suivre',
        notif_login_prompt: 'Connectez-vous pour voir les likes, commentaires et abonnements.',
        notif_login: 'Se connecter',

        // Messages
        msg_title: 'Messages',
        msg_loading: 'Chargement des conversations...',
        msg_loading_msgs: 'Chargement des messages...',
        msg_error: 'Impossible de charger les messages.',
        msg_error_msgs: 'Impossible de charger cette conversation.',
        msg_error_send: 'Impossible d\'envoyer le message.',
        msg_empty_title: 'Aucune conversation',
        msg_empty_body: 'Les messages privés sont disponibles quand deux utilisateurs se suivent mutuellement.',
        msg_no_messages: 'Pas encore de messages',
        msg_mutual_follower: 'Abonné(e) mutuel(le)',
        msg_archived: 'Conversation archivée',
        msg_say_hello: 'Dites bonjour',
        msg_refresh_note: 'Les messages s\'actualisent automatiquement.',
        msg_write: 'Écrire un message',
        msg_start: 'Démarrer la conversation',
        msg_login_prompt: 'Connectez-vous pour discuter avec vos abonnés mutuels.',
        msg_login: 'Se connecter',

        // Media detail
        media_loading: 'Chargement...',
        media_error: 'Impossible de charger ce média.',
        media_go_back: 'Retour',
        media_watch_trailer: 'Voir la bande-annonce',
        media_add_collection: 'Collection',
        media_add_list: 'Liste',
        media_no_lists: 'Aucune liste.',
        media_director: 'Réalisateur',
        media_cast: 'Casting',
        media_similar: 'Vous aimerez aussi',
        media_added: 'Ajouté !',
        media_error_add: 'Impossible d\'ajouter.',

        // List detail
        list_loading: 'Chargement de la liste...',
        list_error: 'Impossible de charger la liste.',
        list_go_back: 'Retour',
        list_public: 'Public',
        list_private: 'Privée',
        list_items: 'éléments',
        list_empty: 'Aucun média dans cette liste pour l\'instant.',
        list_remove_title: 'Retirer ce média ?',
        list_remove_msg: 'Ce média sera retiré de la liste.',
        list_remove_cancel: 'Annuler',
        list_remove_confirm: 'Retirer',

        // Reviews
        review_title: 'Critiques de la communauté',
        review_write: 'Écrire une critique',
        review_edit: 'Modifier ma critique',
        review_close: 'Fermer la critique',
        review_post: 'Publier la critique',
        review_update: 'Mettre à jour',
        review_cancel: 'Annuler',
        review_placeholder: 'Partagez vos impressions... (optionnel)',
        review_empty: 'Aucune critique.',
        review_login: 'Connectez-vous pour écrire une critique.',
        review_delete: 'Supprimer',
        review_ratings: 'note(s)',
        review_no_comments: 'Aucun commentaire.',
        review_loading_comments: 'Chargement des commentaires...',
        review_add_comment: 'Ajouter un commentaire...',
        review_login_comment: 'Connectez-vous pour commenter.',
        review_send: 'Envoyer',
        review_loading: 'Chargement...',
        review_saving: 'Sauvegarde...',
        review_save: 'Enregistrer la critique',
        review_edit_title: 'Modifier votre critique',
        review_write_title: 'Écrire une critique',
        review_error_rating: 'Ajoutez une note ou rédigez une critique d\'abord.',
        review_error_save: 'Impossible d\'enregistrer la critique.',
        review_error_like: 'Impossible de mettre à jour le like.',
        review_error_comment: 'Impossible d\'ajouter le commentaire.',
        review_error_delete_review: 'Impossible de supprimer la critique.',
        review_error_delete_comment: 'Impossible de supprimer le commentaire.',
    },
    en: {
        // Mobile tabs
        tab_home: 'Home',
        tab_search: 'Search',
        tab_feed: 'Feed',
        tab_library: 'Library',
        tab_profile: 'Profile',

        // Profile settings
        settings_title: 'Profile Settings',
        settings_edit_profile: 'Edit profile',
        settings_profile_picture: 'Profile picture',
        settings_image_hint: 'JPEG, PNG, WebP or GIF. Max 5 MB.',
        settings_info: 'Information',
        settings_username: 'Username',
        settings_username_placeholder: 'Your username',
        settings_bio: 'Bio',
        settings_bio_placeholder: 'Tell us a little about yourself...',
        settings_website: 'Website',
        settings_website_placeholder: 'https://yourwebsite.com',
        settings_save: 'Save changes',
        settings_saving: 'Saving...',
        settings_saved: 'Profile saved.',
        settings_avatar_updated: 'Profile picture updated.',
        settings_preferences: 'Preferences',
        settings_theme: 'Theme',
        settings_language: 'Language',
        settings_language_saving: 'Saving...',
        settings_choose: 'Choose',
        settings_upload: 'Upload',
        settings_loading_profile: 'Loading profile...',
        settings_login_required: 'Edit profile',
        settings_login_to_edit: 'Log in to update your profile.',
        settings_log_in: 'Log in',
        settings_unsupported_format: 'Unsupported format. Please use JPEG, PNG, WebP or GIF.',
        settings_too_large: 'Image must not exceed 5 MB.',
        settings_upload_failed: 'Upload failed. Please try again.',
        settings_failed_save: 'Failed to save profile.',
        settings_username_min: 'Username must be between 3 and 50 characters.',
        settings_bio_max: 'Bio cannot exceed',
        settings_bio_max_chars: 'characters.',
        settings_website_invalid: 'Website must start with http:// or https://.',

        // Stats
        stats_title: 'Statistics',
        stats_total: 'Total',
        stats_done: 'Completed',
        stats_reviews: 'Reviews',
        stats_lists: 'Lists',
        stats_content_type: 'CONTENT TYPE',
        stats_movies: 'Movies',
        stats_series: 'Series',
        stats_watch_time: 'WATCH TIME',
        stats_watch_time_sub: 'completed movies',
        stats_avg_rating: 'AVG RATING',
        stats_no_ratings: 'No ratings yet',
        stats_to_watch: 'To Watch',
        stats_watching: 'Watching',
        stats_completed: 'Completed',
        stats_dropped: 'Dropped',

        // Login
        login_welcome_back: 'Welcome back',
        login_subtitle: 'Sign in to your account',
        login_email: 'Email',
        login_password: 'Password',
        login_signing_in: 'Signing in...',
        login_submit: 'Sign In',
        login_or: 'or',
        login_google: 'Continue with Google',
        login_no_account: "Don't have an account?",
        login_sign_up: 'Sign up',

        // Register
        register_title: 'Create an account',
        register_subtitle: 'Join moviemovie today',
        register_username: 'Username',
        register_creating: 'Creating account...',
        register_submit: 'Sign Up',
        register_already: 'Already have an account?',
        register_sign_in: 'Sign in',
        register_pw_min: 'At least 8 characters',
        register_pw_upper: 'One uppercase letter',
        register_pw_lower: 'One lowercase letter',
        register_pw_number: 'One number',

        // Profile
        profile_loading: 'Loading...',
        profile_member_since: 'Member since',
        profile_no_bio: 'No bio yet.',
        profile_followers: 'followers',
        profile_following: 'following',
        profile_edit: 'Edit profile',
        profile_follow: 'Follow',
        profile_following_btn: 'Following',
        profile_unfollow: 'Unfollow',
        profile_saving: 'Saving...',
        profile_my_collection: 'My collection',
        profile_see_all: 'See all',
        profile_no_media: 'No media items yet.',
        profile_my_lists: 'My lists',
        profile_public_lists: 'public lists',
        profile_no_lists: 'No lists yet.',
        profile_no_public_lists: 'No public lists yet.',
        profile_items: 'items',
        profile_lists: 'lists',
        profile_sign_out: 'Sign out',
        profile_followers_title: 'Followers',
        profile_following_title: 'Following',
        profile_no_users: 'No users yet.',
        profile_go_back: 'Go Back',
        profile_unable_load: 'Unable to load this profile.',
        profile_message: 'Message',
        profile_guest: 'Guest',
        profile_guest_browse: 'Browse public content without an account.',
        profile_guest_login_desc: 'Log in to manage your library, reviews, feed, and messages.',
        profile_login: 'Log in',
        profile_create_account: 'Create account',

        // Library
        lib_my_collection: 'My Collection',
        lib_my_lists: 'My Lists',
        lib_loading: 'Loading library...',
        lib_guest_title: 'Library',
        lib_guest_body: 'Log in to manage your collection and lists.',
        lib_all: 'All',
        lib_no_items: 'No media items in this collection.',
        lib_new_list_placeholder: 'New list name...',
        lib_public: 'Public',
        lib_creating: 'Creating...',
        lib_create: '+ Create',
        lib_no_lists: 'No lists yet. Create one above!',
        lib_delete_title: 'Delete this list?',
        lib_delete_msg: 'This action cannot be undone.',
        lib_cancel: 'Cancel',
        lib_delete: 'Delete',
        lib_items: 'items',
        lib_lists: 'lists',

        // Home
        home_title: 'Discover thousands of movies and series in an instant.',
        home_subtitle: 'Search, discover and track your favorite content powered by rich metadata.',
        home_search_placeholder: 'Search for a movie or TV show...',
        home_search_btn: 'Search',
        home_trending: 'Trending Now',
        home_all: 'All',
        home_movies: 'Movies',
        home_series: 'Series',
        home_loading: 'Loading trending content...',
        home_error: 'Failed to load trending content.',
        home_retry: 'Retry',
        home_movie_label: 'Movie',
        home_series_label: 'Series',

        // Mobile login
        mob_login_title: 'Log in',
        mob_login_subtitle: 'Access your library, reviews, feed, and private messages.',
        mob_login_required: 'Email and password are required.',
        mob_login_error: 'Unable to log in.',
        mob_login_new: 'New to moviemovie?',
        mob_login_create: 'Create an account',

        // Mobile register
        mob_register_title: 'Create account',
        mob_register_subtitle: 'Join the community and start building your movie and series library.',
        mob_register_required: 'Username, email, and password are required.',
        mob_register_error: 'Unable to create your account.',
        mob_register_already: 'Already have an account?',
        mob_register_sign_in: 'Log in',

        // Mobile search
        mob_search_placeholder: 'Search movies, series, users, lists...',
        mob_search_movies: 'Movies',
        mob_search_series: 'Series',
        mob_search_users: 'Users',
        mob_search_lists: 'Lists',
        mob_search_sort_popular: 'Popular',
        mob_search_sort_top: 'Top Rated',
        mob_search_sort_newest: 'Newest',
        mob_search_sort_oldest: 'Oldest',
        mob_search_rating_any: 'Any rating',
        mob_search_filters: 'Filters',
        mob_search_year: 'Year',
        mob_search_clear: 'Clear',
        mob_search_all_genres: 'All genres',
        mob_search_discover: 'Search or discover by filters',
        mob_search_searching: 'Searching...',
        mob_search_min_chars: 'Type at least 2 characters',
        mob_search_error: 'Something went wrong',
        mob_search_no_results: 'No results found',
        mob_search_prev: 'Previous',
        mob_search_next: 'Next',
        mob_search_by: 'by',
        mob_search_member: 'moviemovie member',
        mob_search_year_hint: 'Enter a 4-digit year.',
        mob_search_chars_hint: 'Type at least 2 characters to search.',
        mob_search_failed: 'Search failed.',
        mob_search_page_error: 'Enter a page between 1 and',
        mob_search_title: 'Search',

        // Feed
        feed_title: 'Feed',
        feed_loading: 'Loading feed...',
        feed_error: 'Unable to load your feed.',
        feed_empty_title: 'Nothing here yet',
        feed_empty_body: 'Follow users to see their activity here.',
        feed_login_prompt: 'Log in to see recent activity from people you follow.',
        feed_login: 'Log in',
        feed_added_to: 'added this to',
        feed_updated: 'updated their collection',
        feed_reviewed: 'reviewed',
        feed_unknown_title: 'Unknown title',

        // Notifications
        notif_title: 'Notifications',
        notif_loading: 'Loading notifications...',
        notif_error: 'Unable to load notifications.',
        notif_empty_title: 'No notifications yet',
        notif_empty_body: 'You will see likes, review comments, and new followers here.',
        notif_read_all: 'Read all',
        notif_liked: 'liked your review',
        notif_commented: 'commented on your review',
        notif_following: 'started following you',
        notif_login_prompt: 'Log in to see likes, comments, and followers.',
        notif_login: 'Log in',

        // Messages
        msg_title: 'Messages',
        msg_loading: 'Loading conversations...',
        msg_loading_msgs: 'Loading messages...',
        msg_error: 'Unable to load messages.',
        msg_error_msgs: 'Unable to load this conversation.',
        msg_error_send: 'Unable to send message.',
        msg_empty_title: 'No conversations yet',
        msg_empty_body: 'Private messages are available when two users follow each other.',
        msg_no_messages: 'No messages yet',
        msg_mutual_follower: 'Mutual follower',
        msg_archived: 'Conversation archived',
        msg_say_hello: 'Say hello',
        msg_refresh_note: 'Messages refresh automatically.',
        msg_write: 'Write a message',
        msg_start: 'Start the conversation',
        msg_login_prompt: 'Log in to chat with mutual followers.',
        msg_login: 'Log in',

        // Media detail
        media_loading: 'Loading...',
        media_error: 'Failed to load media.',
        media_go_back: 'Go Back',
        media_watch_trailer: 'Watch Trailer',
        media_add_collection: 'Collection',
        media_add_list: 'List',
        media_no_lists: 'No lists yet',
        media_director: 'Director',
        media_cast: 'Cast',
        media_similar: 'You May Also Like',
        media_added: 'Added!',
        media_error_add: 'Unable to add.',

        // List detail
        list_loading: 'Loading list...',
        list_error: 'Failed to load list.',
        list_go_back: 'Go Back',
        list_public: 'Public',
        list_private: 'Private',
        list_items: 'items',
        list_empty: 'No media items in this list yet.',
        list_remove_title: 'Remove this item?',
        list_remove_msg: 'This media will be removed from the list.',
        list_remove_cancel: 'Cancel',
        list_remove_confirm: 'Remove',

        // Reviews
        review_title: 'Community Reviews',
        review_write: 'Write a Review',
        review_edit: 'Edit My Review',
        review_close: 'Close Review',
        review_post: 'Post Review',
        review_update: 'Update Review',
        review_cancel: 'Cancel',
        review_placeholder: 'Share your thoughts... (optional)',
        review_empty: 'No reviews yet.',
        review_login: 'Log in to write your review.',
        review_delete: 'Delete',
        review_ratings: 'ratings',
        review_no_comments: 'No comments yet.',
        review_loading_comments: 'Loading comments...',
        review_add_comment: 'Add a comment...',
        review_login_comment: 'Log in to comment.',
        review_send: 'Send',
        review_loading: 'Loading...',
        review_saving: 'Saving...',
        review_save: 'Save Review',
        review_edit_title: 'Edit Your Review',
        review_write_title: 'Write a Review',
        review_error_rating: 'Add a rating or write a review first.',
        review_error_save: 'Unable to save review.',
        review_error_like: 'Unable to update like.',
        review_error_comment: 'Unable to add comment.',
        review_error_delete_review: 'Unable to delete review.',
        review_error_delete_comment: 'Unable to delete comment.',
    },
};

export function LanguageProvider({ children }) {
    const { user } = useAuth();
    const [language, setLanguageState] = useState(() => {
        const lang = user?.preferred_language;
        return SUPPORTED.includes(lang) ? lang : DEFAULT_LANGUAGE;
    });

    useEffect(() => {
        if (user?.preferred_language && SUPPORTED.includes(user.preferred_language)) {
            setLanguageState(user.preferred_language);
        }
    }, [user?.preferred_language]);

    function setLanguage(lang) {
        if (SUPPORTED.includes(lang)) setLanguageState(lang);
    }

    function t(key) {
        return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS[DEFAULT_LANGUAGE]?.[key] ?? key;
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, SUPPORTED }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider.');
    return ctx;
}
