export const authStyles = {
    page: {
        minHeight: 'calc(100vh - 70px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f7f7f7',
        padding: '24px',
    },
    card: {
        width: '420px',
        backgroundColor: '#fff',
        borderRadius: '20px',
        padding: '48px 40px',
        boxShadow: '0 4px 40px rgba(0,0,0,0.07)',
    },
    brand: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        marginBottom: '36px',
    },
    logo: {
        width: '32px',
        height: '32px',
        backgroundColor: '#111',
        color: '#fff',
        borderRadius: '8px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '700',
        fontSize: '16px',
    },
    brandName: {
        fontSize: '16px',
        fontWeight: '600',
        color: '#111',
        letterSpacing: '-0.3px',
    },
    title: {
        margin: '0 0 6px',
        fontSize: '26px',
        fontWeight: '700',
        color: '#111',
        letterSpacing: '-0.5px',
    },
    subtitle: {
        margin: '0 0 28px',
        fontSize: '14px',
        color: '#999',
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: '7px',
    },
    label: {
        fontSize: '13px',
        fontWeight: '500',
        color: '#444',
    },
    errorBox: {
        backgroundColor: '#fff5f5',
        border: '1px solid #fed7d7',
        borderRadius: '8px',
        padding: '10px 14px',
        fontSize: '13px',
        color: '#c53030',
    },
    button: {
        marginTop: '4px',
        padding: '13px',
        backgroundColor: '#111',
        color: '#fff',
        border: 'none',
        borderRadius: '10px',
        fontSize: '14px',
        fontWeight: '600',
        letterSpacing: '0.2px',
        cursor: 'pointer',
    },
    divider: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        margin: '24px 0',
    },
    dividerLine: {
        flex: 1,
        height: '1px',
        backgroundColor: '#ebebeb',
    },
    dividerText: {
        fontSize: '12px',
        color: '#bbb',
        fontWeight: '500',
    },
    googleButton: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '10px',
        width: '100%',
        padding: '12px',
        border: '1.5px solid #e5e5e5',
        borderRadius: '10px',
        fontSize: '14px',
        fontWeight: '500',
        color: '#333',
        backgroundColor: '#fff',
        textDecoration: 'none',
        boxSizing: 'border-box',
    },
    footer: {
        marginTop: '24px',
        textAlign: 'center',
        fontSize: '13px',
        color: '#999',
    },
    link: {
        color: '#111',
        fontWeight: '600',
        textDecoration: 'none',
    },
};

export const inputStyle = (focused, name) => ({
    width: '100%',
    padding: '12px 14px',
    border: `1.5px solid ${focused === name ? '#111' : '#e5e5e5'}`,
    borderRadius: '10px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: '#fafafa',
    transition: 'border-color 0.2s',
    boxSizing: 'border-box',
});
