const font = "'CircularSp', 'Helvetica Neue', helvetica, arial, sans-serif";

export const authStyles = {
    page: {
        minHeight: 'calc(100vh - 70px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#121212',
        padding: '24px',
        fontFamily: font,
    },
    card: {
        width: '420px',
        backgroundColor: '#181818',
        borderRadius: '8px',
        padding: '48px 40px',
        boxShadow: 'rgba(0,0,0,0.5) 0px 8px 24px',
    },
    brand: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        marginBottom: '36px',
    },
    logo: {
        width: '32px',
        height: '32px',
        backgroundColor: '#1ed760',
        color: '#000',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '700',
        fontSize: '16px',
    },
    brandName: {
        fontSize: '16px',
        fontWeight: '700',
        color: '#fff',
        letterSpacing: '-0.3px',
    },
    title: {
        margin: '0 0 6px',
        fontSize: '26px',
        fontWeight: '700',
        color: '#fff',
        letterSpacing: '-0.5px',
    },
    subtitle: {
        margin: '0 0 28px',
        fontSize: '14px',
        color: '#b3b3b3',
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: '7px',
    },
    label: {
        fontSize: '13px',
        fontWeight: '700',
        color: '#fff',
        letterSpacing: '0.5px',
        textTransform: 'uppercase',
    },
    errorBox: {
        backgroundColor: 'rgba(243,114,127,0.15)',
        border: '1px solid #f3727f',
        borderRadius: '4px',
        padding: '10px 14px',
        fontSize: '13px',
        color: '#f3727f',
    },
    button: {
        marginTop: '4px',
        padding: '14px',
        backgroundColor: '#1ed760',
        color: '#000',
        border: 'none',
        borderRadius: '9999px',
        fontSize: '14px',
        fontWeight: '700',
        letterSpacing: '1.4px',
        textTransform: 'uppercase',
        cursor: 'pointer',
        fontFamily: font,
    },
    divider: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        margin: '24px 0',
    },
    dividerLine: {
        flex: 1,
        height: '1px',
        backgroundColor: '#4d4d4d',
    },
    dividerText: {
        fontSize: '12px',
        color: '#b3b3b3',
        fontWeight: '500',
    },
    googleButton: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '10px',
        width: '100%',
        padding: '12px',
        border: '1px solid #7c7c7c',
        borderRadius: '9999px',
        fontSize: '14px',
        fontWeight: '700',
        color: '#fff',
        backgroundColor: 'transparent',
        textDecoration: 'none',
        boxSizing: 'border-box',
        letterSpacing: '0.5px',
        fontFamily: font,
    },
    footer: {
        marginTop: '24px',
        textAlign: 'center',
        fontSize: '13px',
        color: '#b3b3b3',
    },
    link: {
        color: '#fff',
        fontWeight: '700',
        textDecoration: 'none',
    },
};

export const inputStyle = (focused, name) => ({
    width: '100%',
    padding: '12px 14px',
    border: `1px solid ${focused === name ? '#fff' : '#4d4d4d'}`,
    borderRadius: '4px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: '#1f1f1f',
    color: '#fff',
    transition: 'border-color 0.2s',
    boxSizing: 'border-box',
    fontFamily: "'CircularSp', 'Helvetica Neue', helvetica, arial, sans-serif",
});
