import { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';

const LanguageContext = createContext(null);

const SUPPORTED = ['fr', 'en'];
const DEFAULT_LANGUAGE = 'en';

const TRANSLATIONS = {
    fr: {
        // Navigation
        nav_explore: 'Explorer',
        nav_feed: 'Fil d\'actualité',
        nav_collection: 'Collection',
        nav_lists: 'Listes',
        nav_profile: 'Profil',
        nav_sign_in: 'Connexion',
        nav_sign_up: 'Inscription',
        nav_notifications: 'Notifications',
        nav_messages: 'Messages',
        nav_mark_all_read: 'Tout marquer comme lu',
        nav_no_notifications: 'Aucune notification',
        nav_loading: 'Chargement…',
        nav_see_all: 'Voir toutes les notifications',

        // Mobile tabs
        tab_home: 'Accueil',
        tab_search: 'Rechercher',
        tab_feed: 'Actualités',
        tab_library: 'Bibliothèque',
        tab_profile: 'Profil',

        // Profile settings
        settings_title: 'Paramètres du profil',
        settings_back: '← Retour au tableau de bord',
        settings_edit_profile: 'Modifier le profil',
        settings_profile_picture: 'Photo de profil',
        settings_choose_image: 'Choisir une image',
        settings_confirm_upload: '✓ Confirmer l\'upload',
        settings_uploading: 'Envoi…',
        settings_image_hint: 'JPEG, PNG, WebP ou GIF · max 5 Mo',
        settings_info: 'Informations',
        settings_username: 'Nom d\'utilisateur',
        settings_username_placeholder: 'Votre pseudo',
        settings_bio: 'Bio',
        settings_bio_placeholder: 'Parlez-nous un peu de vous...',
        settings_website: 'Site web',
        settings_website_placeholder: 'https://votresite.com',
        settings_save: 'Enregistrer les modifications',
        settings_saving: 'Enregistrement...',
        settings_saved: 'Profil enregistré !',
        settings_avatar_updated: 'Photo de profil mise à jour !',
        settings_preferences: 'Préférences',
        settings_theme: 'Thème',
        settings_theme_dark: 'Mode sombre actif',
        settings_theme_light: 'Mode clair actif',
        settings_language: 'Langue',
        settings_language_saving: 'Sauvegarde...',
        settings_data_title: 'Mes données (RGPD)',
        settings_data_desc: 'Téléchargez votre collection et vos critiques en CSV ou JSON.',
        settings_export_csv: 'Exporter CSV',
        settings_export_json: 'Exporter JSON',
        settings_exporting: 'Export...',
        settings_danger_zone: 'Zone dangereuse',
        settings_delete_account: 'Supprimer mon compte',
        settings_delete_desc: 'La suppression de votre compte est définitive. Toutes vos données (collection, critiques, commentaires) seront effacées.',
        settings_confirm_deletion: 'Confirmer la suppression',
        settings_confirm_deletion_msg: 'Êtes-vous sûr(e) de vouloir supprimer votre compte ? Cette action est irréversible.',
        settings_cancel: 'Annuler',
        settings_yes_delete: 'Oui, supprimer',
        settings_unsupported_format: 'Format non supporté. Utilisez JPEG, PNG, WebP ou GIF.',
        settings_too_large: 'L\'image ne doit pas dépasser 5 Mo.',
        settings_upload_failed: 'Échec de l\'upload. Réessayez.',
        settings_failed_save: 'Impossible d\'enregistrer le profil.',
        settings_failed_delete: 'Impossible de supprimer le compte.',
        settings_failed_export: 'Échec de l\'export. Réessayez.',
        settings_choose: 'Choisir',
        settings_upload: 'Envoyer',
        settings_loading_profile: 'Chargement du profil...',
        settings_login_required: 'Connexion requise',
        settings_login_to_edit: 'Connectez-vous pour modifier votre profil.',
        settings_log_in: 'Se connecter',

        // Stats
        stats_title: 'Statistiques',
        stats_total: 'Total',
        stats_in_collection: 'dans la collection',
        stats_done: 'Terminés',
        stats_finished: 'terminés',
        stats_reviews: 'Critiques',
        stats_written: 'rédigées',
        stats_lists: 'Listes',
        stats_created: 'créées',
        stats_content_type: 'Type de contenu',
        stats_movies: 'Films',
        stats_series: 'Séries',
        stats_watch_time: 'Temps de visionnage',
        stats_watch_time_sub: 'des films terminés',
        stats_avg_rating: 'Note moyenne',
        stats_no_ratings: 'Pas encore noté',
        stats_to_watch: 'À voir',
        stats_watching: 'En cours',
        stats_completed: 'Terminés',
        stats_dropped: 'Abandonnés',

        // Login
        login_welcome_back: 'Bienvenue',
        login_subtitle: 'Connectez-vous à votre compte',
        login_session_expired: 'Votre session a expiré. Veuillez vous reconnecter.',
        login_email: 'Email',
        login_password: 'Mot de passe',
        login_signing_in: 'Connexion...',
        login_submit: 'Se connecter',
        login_or: 'ou',
        login_google: 'Continuer avec Google',
        login_no_account: 'Pas de compte ?',
        login_sign_up: "S'inscrire",

        // Register
        register_title: 'Créer un compte',
        register_subtitle: 'Rejoignez Moviemovie',
        register_username: "Nom d'utilisateur",
        register_creating: 'Création en cours...',
        register_submit: "S'inscrire",
        register_already: 'Déjà un compte ?',
        register_sign_in: 'Se connecter',
        register_pw_min: 'Au moins 8 caractères',
        register_pw_upper: 'Une lettre majuscule',
        register_pw_lower: 'Une lettre minuscule',
        register_pw_number: 'Un chiffre',

        // Profile / Dashboard
        profile_loading: 'Chargement...',
        profile_member_since: 'Membre depuis',
        profile_no_bio: 'Pas encore de bio.',
        profile_followers: 'abonnés',
        profile_following: 'abonnements',
        profile_edit: 'Modifier le profil',
        profile_follow: 'Suivre',
        profile_following_btn: 'Abonné(e)',
        profile_unfollow: 'Se désabonner',
        profile_saving: 'Sauvegarde...',
        profile_my_collection: 'Ma collection',
        profile_see_all: 'Voir tout',
        profile_no_media: 'Aucun média pour l\'instant.',
        profile_my_lists: 'Mes listes',
        profile_public_lists: 'listes publiques',
        profile_no_lists: 'Aucune liste pour l\'instant.',
        profile_no_public_lists: 'Aucune liste publique.',
        profile_items: 'éléments',
        profile_lists: 'listes',
        profile_sign_out: 'Déconnexion',
        profile_followers_title: 'Abonnés',
        profile_following_title: 'Abonnements',
        profile_no_users: 'Aucun utilisateur.',
        profile_go_back: 'Retour',
        profile_unable_load: 'Impossible de charger ce profil.',
        profile_message: 'Message',
        profile_guest: 'Invité',
        profile_guest_browse: 'Parcourez le contenu public sans compte.',
        profile_guest_login_desc: 'Connectez-vous pour gérer votre bibliothèque, critiques, fil d\'actualité et messages.',
        profile_login: 'Se connecter',
        profile_create_account: 'Créer un compte',

        // Feed
        feed_title: 'Fil d\'actualité',
        feed_loading: 'Chargement du fil...',
        feed_error: 'Impossible de charger votre fil.',
        feed_empty_title: 'Rien pour l\'instant',
        feed_empty_body: 'Suivez des utilisateurs pour voir leur activité ici.',
        feed_added_to: 'a ajouté dans',
        feed_updated: 'a mis à jour sa collection',
        feed_reviewed: 'a écrit une critique',
        feed_just_now: 'à l\'instant',
        feed_min_ago: 'min',
        feed_hour_ago: 'h',
        feed_day_ago: 'j',

        // Notifications
        notif_title: 'Notifications',
        notif_loading: 'Chargement des notifications...',
        notif_error: 'Impossible de charger les notifications.',
        notif_empty_title: 'Aucune notification',
        notif_empty_body: 'Vous serez notifié(e) quand quelqu\'un aime ou commente votre critique, ou vous suit.',
        notif_mark_all_read: 'Tout marquer comme lu',
        notif_liked: 'a aimé votre critique',
        notif_commented: 'a commenté votre critique',
        notif_following: 'a commencé à vous suivre',

        // Messages
        msg_title: 'Messages',
        msg_loading: 'Chargement des conversations...',
        msg_loading_msgs: 'Chargement des messages...',
        msg_error: 'Impossible de charger les conversations.',
        msg_error_msgs: 'Impossible de charger cette conversation.',
        msg_error_send: 'Impossible d\'envoyer le message.',
        msg_empty_title: 'Aucune conversation',
        msg_empty_body: 'Les messages privés sont disponibles quand deux utilisateurs se suivent mutuellement.',
        msg_no_mutual: 'Aucun abonné mutuel',
        msg_no_mutual_body: 'Suivez-vous mutuellement pour démarrer une discussion privée.',
        msg_mutual_follower: 'Abonné(e) mutuel(le)',
        msg_archived: 'Conversation archivée',
        msg_say_hello: 'Dites bonjour',
        msg_refresh_note: 'Les messages s\'actualisent automatiquement toutes les 5 secondes.',
        msg_write: 'Écrire un message',
        msg_send: 'Envoyer',
        msg_choose_title: 'Choisissez quelqu\'un avec qui discuter',
        msg_choose_body: 'Les messages privés sont disponibles quand deux utilisateurs se suivent mutuellement.',
        msg_readonly: 'Vous pouvez lire cette conversation, mais l\'envoi de messages nécessite un abonnement mutuel.',
        msg_no_messages: 'Pas encore de messages',
        msg_start: 'Démarrer la conversation',

        // Media detail
        media_loading: 'Chargement...',
        media_error: 'Impossible de charger ce média.',
        media_go_back: 'Retour',
        media_watch_trailer: '▶ Voir la bande-annonce',
        media_add_collection: '+ Collection',
        media_add_list: '+ Liste',
        media_new_list: 'Nouvelle liste',
        media_no_lists: 'Aucune liste.',
        media_director: 'Réalisateur',
        media_cast: 'Casting',
        media_similar: 'Vous aimerez aussi',
        media_added: 'Ajouté !',
        media_error_add: 'Impossible d\'ajouter.',

        // List detail
        list_loading: 'Chargement...',
        list_error: 'Impossible de charger la liste.',
        list_go_back: 'Retour',
        list_public: 'Public',
        list_private: 'Privée',
        list_items: 'éléments',
        list_empty: 'Aucun média dans cette liste pour l\'instant.',
        list_remove_title: 'Retirer ce média de la liste ?',
        list_remove_msg: 'Ce média sera retiré de la liste.',
        list_remove_cancel: 'Annuler',
        list_remove_confirm: 'Retirer',
        list_back: '← Mes listes',

        // Lists page (web)
        lists_title: 'Mes Listes',
        lists_loading: 'Chargement...',
        lists_error: 'Impossible de charger les listes.',
        lists_new_placeholder: 'Nom de la nouvelle liste...',
        lists_public: 'Publique',
        lists_creating: 'Création...',
        lists_create: '+ Créer',
        lists_empty: 'Aucune liste. Créez-en une ci-dessus !',
        lists_edit: 'Modifier',
        lists_delete: 'Supprimer',
        lists_delete_confirm: 'Supprimer cette liste ?',

        // Collection page (web)
        col_title: 'Ma Collection',
        col_all: 'Tout',
        col_loading: 'Chargement...',
        col_empty: 'Aucun média dans cette collection.',

        // Reviews
        review_title: 'Critiques de la communauté',
        review_write: 'Écrire une critique',
        review_edit: 'Modifier ma critique',
        review_close: 'Fermer la critique',
        review_post: 'Publier la critique',
        review_update: 'Mettre à jour',
        review_cancel: 'Annuler',
        review_placeholder: 'Partagez vos impressions... (optionnel)',
        review_empty: 'Aucune critique. Soyez le premier !',
        review_login: 'Connectez-vous pour écrire une critique.',
        review_delete: 'Supprimer',
        review_report: 'Signaler',
        review_reporting: 'Signalement...',
        review_report_reason: 'Pourquoi signalez-vous cette critique ? (optionnel)',
        review_report_success: 'Signalement envoye.',
        review_ratings: 'note(s)',
        review_no_comments: 'Aucun commentaire.',
        review_loading_comments: 'Chargement des commentaires...',
        review_add_comment: 'Ajouter un commentaire...',
        review_login_comment: 'Connectez-vous pour commenter.',
        review_send: 'Envoyer',
        review_loading: 'Chargement...',
        review_saving: 'Sauvegarde...',
        review_save: 'Enregistrer la critique',
        review_edit_title: 'Modifier votre critique',
        review_write_title: 'Écrire une critique',
        review_error_rating: 'Ajoutez une note ou rédigez une critique d\'abord.',
        review_error_save: 'Impossible d\'enregistrer la critique.',
        review_error_like: 'Impossible de mettre à jour le like.',
        review_error_comment: 'Impossible d\'ajouter le commentaire.',
        review_error_report: 'Impossible de signaler cette critique.',
        review_error_delete_review: 'Impossible de supprimer la critique.',
        review_error_delete_comment: 'Impossible de supprimer le commentaire.',

        // Search / Explore (web)
        search_title: 'Explorer',
        search_subtitle: 'Recherchez films, séries, utilisateurs et listes publiques.',
        search_tab_media: 'Films & Séries',
        search_tab_people: 'Personnes',
        search_tab_lists: 'Listes',
        search_cat_movies: 'Films',
        search_cat_series: 'Séries',
        search_cat_users: 'Utilisateurs',
        search_cat_lists: 'Listes',
        search_filters: 'Filtres',
        search_clear: 'Effacer',
        search_placeholder: 'Un titre de film ou de série... (optionnel)',
        search_loading: 'Recherche...',
        search_btn: 'Rechercher',
        search_reset: 'Réinitialiser',
        search_type: 'Type',
        search_movie: 'Film',
        search_tv: 'Série',
        search_year: 'Année',
        search_genre: 'Genre',
        search_min_rating: 'Note min.',
        search_sort_by: 'Trier par',
        search_all_genres: 'Tous les genres',
        search_sort_popularity: 'Popularité',
        search_sort_top_rated: 'Mieux notés',
        search_sort_newest: 'Date de sortie (récent)',
        search_sort_oldest: 'Date de sortie (ancien)',
        search_sort_box_office: 'Box-Office',
        search_all_ratings: 'Toutes les notes',
        search_results: 'résultat(s) trouvé(s)',
        search_no_results: 'Aucun résultat pour ces filtres. Essayez d\'ajuster votre recherche.',
        search_start_title: 'Commencer à explorer',
        search_start_body: 'Entrez un titre ou choisissez des filtres ci-dessus, puis cliquez sur Rechercher.',
        search_no_content: 'Aucun contenu disponible.',
        search_prev: '← Précédent',
        search_next: 'Suivant →',
        search_user_placeholder: 'Rechercher par nom d\'utilisateur...',
        search_no_users: 'Aucun utilisateur trouvé pour cette recherche.',
        search_users_title: 'Trouver un utilisateur',
        search_users_body: 'Recherchez par nom d\'utilisateur pour découvrir d\'autres membres de la communauté.',
        search_list_placeholder: 'Rechercher des listes publiques par nom...',
        search_no_lists: 'Aucune liste publique trouvée.',
        search_lists_title: 'Trouver une liste',
        search_lists_body: 'Parcourez les listes publiques créées par la communauté.',
        search_item: 'élément',
        search_items: 'éléments',
        search_bar_placeholder: 'Rechercher un film ou une série...',
        search_quick: 'Recherche rapide',
        search_no_results_query: 'Aucun résultat pour',
        search_load_more: 'Chargement...',
        search_see_all: 'Rechercher — Voir tous les résultats',

        // Not Found (404)
        notfound_error: 'Erreur 404',
        notfound_title: 'Page introuvable',
        notfound_body: 'La page que vous cherchez n\'existe pas ou a peut-être été déplacée.',
        notfound_home: 'Retour à l\'accueil',
        notfound_explore: 'Explorer les titres',

        // Footer
        footer_desc: 'Suivez, découvrez et partagez vos films et séries préférés.',
        footer_discover: 'Découvrir',
        footer_account: 'Compte',
        footer_settings: 'Paramètres',
        footer_privacy: 'Politique de confidentialité',
        footer_terms: 'Conditions d\'utilisation',
        footer_legal: 'Mentions légales',

        // Home page (landing)
        hero_title: 'Découvrez des milliers de films et séries en un instant.',
        hero_subtitle: 'Recherchez, découvrez et suivez vos contenus favoris grâce à des métadonnées riches.',
        hero_search_placeholder: 'Rechercher un film ou une série...',
        trending_eyebrow: 'À la une',
        trending_title: 'Tendances',
        trending_all: 'Tout',
        trending_movies: 'Films',
        trending_series: 'Séries',
        trending_error: 'Impossible de charger les tendances.',
        trending_retry: 'Réessayer',
        home_view_details: 'Voir les détails →',
        features_eyebrow: 'Pourquoi moviemovie ?',
        features_title: 'Tout ce dont vous avez besoin',
        feature1_title: 'Recherche intelligente',
        feature1_desc: 'Trouvez n\'importe quel film ou série en quelques secondes grâce à notre moteur combinant cache local et TMDB.',
        feature2_title: 'Notes & Critiques',
        feature2_desc: 'Parcourez les notes et critiques de la communauté pour ne manquer aucun chef-d\'œuvre.',
        feature3_title: 'Pages détaillées',
        feature3_desc: 'Accédez aux synopsis, castings, réalisateurs et plus encore pour chaque titre.',
        feature4_title: 'Expérience responsive',
        feature4_desc: 'Une interface fluide sur ordinateur, tablette et mobile pour chercher partout.',
        cta_title: 'Prêt(e) à explorer ?',
        cta_subtitle: 'Créez votre compte gratuit et accédez à la base de données complète.',
        cta_btn_primary: 'Créer un compte gratuit',
        cta_btn_ghost: 'J\'ai déjà un compte',

        // OAuth
        oauth_loading: 'Connexion en cours...',
    },
    en: {
        // Navigation
        nav_explore: 'Explore',
        nav_feed: 'Feed',
        nav_collection: 'Collection',
        nav_lists: 'Lists',
        nav_profile: 'Profile',
        nav_sign_in: 'Sign in',
        nav_sign_up: 'Sign up',
        nav_notifications: 'Notifications',
        nav_messages: 'Messages',
        nav_mark_all_read: 'Mark all as read',
        nav_no_notifications: 'No notifications yet',
        nav_loading: 'Loading…',
        nav_see_all: 'See all notifications',

        // Mobile tabs
        tab_home: 'Home',
        tab_search: 'Search',
        tab_feed: 'Feed',
        tab_library: 'Library',
        tab_profile: 'Profile',

        // Profile settings
        settings_title: 'Profile Settings',
        settings_back: '← Back to dashboard',
        settings_edit_profile: 'Edit profile',
        settings_profile_picture: 'Profile picture',
        settings_choose_image: 'Choose an image',
        settings_confirm_upload: '✓ Confirm upload',
        settings_uploading: 'Uploading…',
        settings_image_hint: 'JPEG, PNG, WebP or GIF · max 5 MB',
        settings_info: 'Information',
        settings_username: 'Username',
        settings_username_placeholder: 'Your username',
        settings_bio: 'Bio',
        settings_bio_placeholder: 'Tell us a little about yourself...',
        settings_website: 'Website',
        settings_website_placeholder: 'https://yourwebsite.com',
        settings_save: 'Save changes',
        settings_saving: 'Saving...',
        settings_saved: 'Profile saved!',
        settings_avatar_updated: 'Profile picture updated!',
        settings_preferences: 'Preferences',
        settings_theme: 'Theme',
        settings_theme_dark: 'Dark mode is active',
        settings_theme_light: 'Light mode is active',
        settings_language: 'Language',
        settings_language_saving: 'Saving...',
        settings_data_title: 'My data (GDPR)',
        settings_data_desc: 'Download your collection and reviews in CSV or JSON format.',
        settings_export_csv: 'Export CSV',
        settings_export_json: 'Export JSON',
        settings_exporting: 'Exporting...',
        settings_danger_zone: 'Danger zone',
        settings_delete_account: 'Delete my account',
        settings_delete_desc: 'Deleting your account is permanent. All your data (collection, reviews, comments) will be erased.',
        settings_confirm_deletion: 'Confirm deletion',
        settings_confirm_deletion_msg: 'Are you sure you want to delete your account? This action is irreversible.',
        settings_cancel: 'Cancel',
        settings_yes_delete: 'Yes, delete',
        settings_unsupported_format: 'Unsupported format. Please use JPEG, PNG, WebP or GIF.',
        settings_too_large: 'Image must not exceed 5 MB.',
        settings_upload_failed: 'Upload failed. Please try again.',
        settings_failed_save: 'Failed to save profile.',
        settings_failed_delete: 'Failed to delete account.',
        settings_failed_export: 'Export failed. Please try again.',
        settings_choose: 'Choose',
        settings_upload: 'Upload',
        settings_loading_profile: 'Loading profile...',
        settings_login_required: 'Edit profile',
        settings_login_to_edit: 'Log in to update your profile.',
        settings_log_in: 'Log in',

        // Stats
        stats_title: 'Statistics',
        stats_total: 'Total',
        stats_in_collection: 'in collection',
        stats_done: 'Completed',
        stats_finished: 'finished',
        stats_reviews: 'Reviews',
        stats_written: 'written',
        stats_lists: 'Lists',
        stats_created: 'created',
        stats_content_type: 'Content type',
        stats_movies: 'Movies',
        stats_series: 'Series',
        stats_watch_time: 'Watch time',
        stats_watch_time_sub: 'from completed movies',
        stats_avg_rating: 'Avg. rating',
        stats_no_ratings: 'No ratings yet',
        stats_to_watch: 'To Watch',
        stats_watching: 'Watching',
        stats_completed: 'Completed',
        stats_dropped: 'Dropped',

        // Login
        login_welcome_back: 'Welcome back',
        login_subtitle: 'Sign in to your account',
        login_session_expired: 'Your session has expired. Please sign in again.',
        login_email: 'Email',
        login_password: 'Password',
        login_signing_in: 'Signing in...',
        login_submit: 'Sign In',
        login_or: 'or',
        login_google: 'Continue with Google',
        login_no_account: "Don't have an account?",
        login_sign_up: 'Sign up',

        // Register
        register_title: 'Create an account',
        register_subtitle: 'Join Moviemovie today',
        register_username: 'Username',
        register_creating: 'Creating account...',
        register_submit: 'Sign Up',
        register_already: 'Already have an account?',
        register_sign_in: 'Sign in',
        register_pw_min: 'At least 8 characters',
        register_pw_upper: 'One uppercase letter',
        register_pw_lower: 'One lowercase letter',
        register_pw_number: 'One number',

        // Profile / Dashboard
        profile_loading: 'Loading...',
        profile_member_since: 'Member since',
        profile_no_bio: 'No bio yet.',
        profile_followers: 'followers',
        profile_following: 'following',
        profile_edit: 'Edit profile',
        profile_follow: 'Follow',
        profile_following_btn: 'Following',
        profile_unfollow: 'Unfollow',
        profile_saving: 'Saving...',
        profile_my_collection: 'My collection',
        profile_see_all: 'See all',
        profile_no_media: 'No media items yet.',
        profile_my_lists: 'My lists',
        profile_public_lists: 'public lists',
        profile_no_lists: 'No lists yet.',
        profile_no_public_lists: 'No public lists yet.',
        profile_items: 'items',
        profile_lists: 'lists',
        profile_sign_out: 'Sign Out',
        profile_followers_title: 'Followers',
        profile_following_title: 'Following',
        profile_no_users: 'No users yet.',
        profile_go_back: 'Go Back',
        profile_unable_load: 'Unable to load this profile.',
        profile_message: 'Message',
        profile_guest: 'Guest',
        profile_guest_browse: 'Browse public content without an account.',
        profile_guest_login_desc: 'Log in to manage your library, reviews, feed, and private messages.',
        profile_login: 'Log in',
        profile_create_account: 'Create account',

        // Feed
        feed_title: 'Feed',
        feed_loading: 'Loading feed...',
        feed_error: 'Unable to load your feed.',
        feed_empty_title: 'Nothing here yet',
        feed_empty_body: 'Follow users to see their activity here.',
        feed_added_to: 'added this to',
        feed_updated: 'updated their collection',
        feed_reviewed: 'reviewed',
        feed_just_now: 'just now',
        feed_min_ago: 'm ago',
        feed_hour_ago: 'h ago',
        feed_day_ago: 'd ago',

        // Notifications
        notif_title: 'Notifications',
        notif_loading: 'Loading notifications...',
        notif_error: 'Unable to load notifications.',
        notif_empty_title: 'No notifications yet',
        notif_empty_body: 'You\'ll be notified when someone likes or comments on your review, or follows you.',
        notif_mark_all_read: 'Mark all as read',
        notif_liked: 'liked your review',
        notif_commented: 'commented on your review',
        notif_following: 'started following you',

        // Messages
        msg_title: 'Messages',
        msg_loading: 'Loading conversations...',
        msg_loading_msgs: 'Loading messages...',
        msg_error: 'Unable to load conversations.',
        msg_error_msgs: 'Unable to load this conversation.',
        msg_error_send: 'Unable to send message.',
        msg_empty_title: 'No conversations yet',
        msg_empty_body: 'Private messages are available when two users follow each other.',
        msg_no_mutual: 'No mutual followers',
        msg_no_mutual_body: 'Follow each other to start a private chat.',
        msg_mutual_follower: 'Mutual follower',
        msg_archived: 'Conversation archived',
        msg_say_hello: 'Say hello',
        msg_refresh_note: 'Messages refresh automatically every 5 seconds.',
        msg_write: 'Write a message',
        msg_send: 'Send',
        msg_choose_title: 'Choose someone to chat with',
        msg_choose_body: 'Private messages are available when two users follow each other.',
        msg_readonly: 'You can read this conversation, but new messages require mutual follow.',
        msg_no_messages: 'No messages yet',
        msg_start: 'Start the conversation',

        // Media detail
        media_loading: 'Loading...',
        media_error: 'Failed to load media.',
        media_go_back: 'Go Back',
        media_watch_trailer: '▶ Watch Trailer',
        media_add_collection: '+ Collection',
        media_add_list: '+ List',
        media_new_list: 'New list',
        media_no_lists: 'No lists yet.',
        media_director: 'Director',
        media_cast: 'Cast',
        media_similar: 'You May Also Like',
        media_added: 'Added!',
        media_error_add: 'Unable to add.',

        // List detail
        list_loading: 'Loading...',
        list_error: 'Failed to load list.',
        list_go_back: 'Go Back',
        list_public: 'Public',
        list_private: 'Private',
        list_items: 'items',
        list_empty: 'No media items in this list yet.',
        list_remove_title: 'Remove this media item from the list?',
        list_remove_msg: 'This media will be removed from the list.',
        list_remove_cancel: 'Cancel',
        list_remove_confirm: 'Remove',
        list_back: '← My Lists',

        // Lists page (web)
        lists_title: 'My Lists',
        lists_loading: 'Loading...',
        lists_error: 'Failed to load lists.',
        lists_new_placeholder: 'New list name…',
        lists_public: 'Public',
        lists_creating: 'Creating…',
        lists_create: '+ Create',
        lists_empty: 'No lists yet. Create one above!',
        lists_edit: 'Edit',
        lists_delete: 'Delete',
        lists_delete_confirm: 'Delete this list?',

        // Collection page (web)
        col_title: 'My Collection',
        col_all: 'All',
        col_loading: 'Loading...',
        col_empty: 'No media items in this collection.',

        // Reviews
        review_title: 'Community Reviews',
        review_write: 'Write a Review',
        review_edit: 'Edit My Review',
        review_close: 'Close Review',
        review_post: 'Post Review',
        review_update: 'Update Review',
        review_cancel: 'Cancel',
        review_placeholder: 'Share your thoughts… (optional)',
        review_empty: 'No reviews yet. Be the first!',
        review_login: 'Log in to write a review.',
        review_delete: 'Delete',
        review_report: 'Report',
        review_reporting: 'Reporting...',
        review_report_reason: 'Why are you reporting this review? (optional)',
        review_report_success: 'Report sent.',
        review_ratings: 'ratings',
        review_no_comments: 'No comments yet.',
        review_loading_comments: 'Loading comments...',
        review_add_comment: 'Add a comment…',
        review_login_comment: 'Log in to comment.',
        review_send: 'Send',
        review_loading: 'Loading…',
        review_saving: 'Saving...',
        review_save: 'Save Review',
        review_edit_title: 'Edit Your Review',
        review_write_title: 'Write a Review',
        review_error_rating: 'Add a rating or write a review first.',
        review_error_save: 'Unable to save review.',
        review_error_like: 'Unable to update like.',
        review_error_comment: 'Unable to add comment.',
        review_error_report: 'Unable to report this review.',
        review_error_delete_review: 'Unable to delete review.',
        review_error_delete_comment: 'Unable to delete comment.',

        // Search / Explore (web)
        search_title: 'Explore',
        search_subtitle: 'Search across movies, TV shows, users, and public lists.',
        search_tab_media: 'Movies & TV shows',
        search_tab_people: 'People',
        search_tab_lists: 'Lists',
        search_cat_movies: 'Movies',
        search_cat_series: 'Series',
        search_cat_users: 'Users',
        search_cat_lists: 'Lists',
        search_filters: 'Filters',
        search_clear: 'Clear',
        search_placeholder: 'A movie or TV show title… (optional)',
        search_loading: 'Searching…',
        search_btn: 'Search',
        search_reset: 'Reset',
        search_type: 'Type',
        search_movie: 'Movie',
        search_tv: 'TV Show',
        search_year: 'Year',
        search_genre: 'Genre',
        search_min_rating: 'Min Rating',
        search_sort_by: 'Sort By',
        search_all_genres: 'All genres',
        search_sort_popularity: 'Popularity',
        search_sort_top_rated: 'Top Rated',
        search_sort_newest: 'Release Date (Newest)',
        search_sort_oldest: 'Release Date (Oldest)',
        search_sort_box_office: 'Box Office',
        search_all_ratings: 'All ratings',
        search_results: 'result(s) found',
        search_no_results: 'No results found for these filters. Try adjusting your search.',
        search_start_title: 'Start Exploring',
        search_start_body: 'Enter a title or choose filters above, then click Search.',
        search_no_content: 'No content available.',
        search_prev: '← Previous',
        search_next: 'Next →',
        search_user_placeholder: 'Search by username…',
        search_no_users: 'No users found for this query.',
        search_users_title: 'Find a user',
        search_users_body: 'Search by username to discover other members of the community.',
        search_list_placeholder: 'Search public lists by name…',
        search_no_lists: 'No public lists found for this query.',
        search_lists_title: 'Find a list',
        search_lists_body: 'Browse public lists created by the community.',
        search_item: 'item',
        search_items: 'items',
        search_bar_placeholder: 'Search for a movie or TV show...',
        search_quick: 'Quick search',
        search_no_results_query: 'No results for',
        search_load_more: 'Loading more...',
        search_see_all: 'Search - See all results',

        // Not Found (404)
        notfound_error: 'Error 404',
        notfound_title: 'Page not found',
        notfound_body: 'The page you\'re looking for doesn\'t exist or may have been moved.',
        notfound_home: 'Back to home',
        notfound_explore: 'Explore titles',

        // Footer
        footer_desc: 'Track, discover, and share your favourite films and series.',
        footer_discover: 'Discover',
        footer_account: 'Account',
        footer_settings: 'Settings',
        footer_privacy: 'Privacy Policy',
        footer_terms: 'Terms of Service',
        footer_legal: 'Legal Notice',

        // Home page (landing)
        hero_title: 'Discover thousands of movies and series in an instant.',
        hero_subtitle: 'Search, discover and track your favorite content powered by rich metadata.',
        hero_search_placeholder: 'Search for a movie or TV show...',
        trending_eyebrow: 'Featured',
        trending_title: 'Trending Now',
        trending_all: 'All',
        trending_movies: 'Movies',
        trending_series: 'Series',
        trending_error: 'Failed to load trending content.',
        trending_retry: 'Retry',
        home_view_details: 'View details →',
        features_eyebrow: 'Why moviemovie?',
        features_title: 'Everything you need',
        feature1_title: 'Smart Search',
        feature1_desc: 'Find any film or series in seconds with our search engine combining local cache and TMDB.',
        feature2_title: 'Ratings & Reviews',
        feature2_desc: 'Browse community scores and reviews to never miss a masterpiece.',
        feature3_title: 'Detailed Pages',
        feature3_desc: 'Access synopses, casts, directors, and more for every title.',
        feature4_title: 'Responsive Experience',
        feature4_desc: 'A fluid interface on desktop, tablet, and mobile so you can search anywhere.',
        cta_title: 'Ready to explore?',
        cta_subtitle: 'Create your free account and get access to the full database.',
        cta_btn_primary: 'Create a free account',
        cta_btn_ghost: 'I already have an account',

        // OAuth
        oauth_loading: 'Signing in...',
    },
};

function resolveInitialLanguage(user) {
    const lang = user?.preferred_language;
    return SUPPORTED.includes(lang) ? lang : DEFAULT_LANGUAGE;
}

export function LanguageProvider({ children }) {
    const { user } = useAuth();
    const [language, setLanguageState] = useState(() => resolveInitialLanguage(user));

    useEffect(() => {
        if (user?.preferred_language && SUPPORTED.includes(user.preferred_language)) {
            setLanguageState(user.preferred_language);
        }
    }, [user?.preferred_language]);

    function setLanguage(lang) {
        if (SUPPORTED.includes(lang)) setLanguageState(lang);
    }

    function t(key) {
        return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS[DEFAULT_LANGUAGE]?.[key] ?? key;
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, SUPPORTED }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
